<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="47" started-at="2018-07-14T06:06:25Z" finished-at="2018-07-14T06:06:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="47" started-at="2018-07-14T06:06:25Z" finished-at="2018-07-14T06:06:25Z">
      <class name="com.scp.buisiness.UserLogin">
        <test-method status="SKIP" signature="authenticate(java.lang.String, java.lang.String)[pri:0, instance:com.scp.buisiness.UserLogin@1375618]" name="authenticate" duration-ms="0" started-at="2018-07-14T11:36:25Z" data-provider="credentials" finished-at="2018-07-14T11:36:25Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public static void com.scp.buisiness.UserLogin.authenticate(java.lang.String,java.lang.String) throws javax.xml.bind.ValidationException requires a @DataProvider named : credentials]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public static void com.scp.buisiness.UserLogin.authenticate(java.lang.String,java.lang.String) throws javax.xml.bind.ValidationException requires a @DataProvider named : credentials
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- authenticate -->
      </class> <!-- com.scp.buisiness.UserLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
